/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        "on-surface-variant": "#434655",
        "on-error": "#ffffff",
        "outline-variant": "#c3c6d7",
        "surface-container-highest": "#e2e1ee",
        "surface-dim": "#d9d9e5",
        "on-primary-container": "#ffffff",
        "secondary-fixed-dim": "#c3c6ce",
        "on-primary-fixed": "#00174c",
        "on-primary-fixed-variant": "#003da9",
        "on-tertiary-container": "#ffffff",
        "inverse-primary": "#b4c5ff",
        "surface-tint": "#0552db",
        "surface": "#faf8ff",
        "outline": "#737686",
        "surface-container-high": "#e7e7f4",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "inverse-on-surface": "#f0f0fc",
        "error": "#ba1a1a",
        "primary-container": "#366df5",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-error-container": "#93000a",
        "tertiary": "#a13f00",
        "surface-container": "#ededf9",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2e3039",
        "secondary-container": "#dfe2ea",
        "surface-variant": "#e2e1ee",
        "secondary-fixed": "#dfe2ea",
        "on-background": "#191b24",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-container": "#c85208",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f2ff",
        "tertiary-fixed-dim": "#ffb694",
        "on-surface": "#191b24",
        "on-tertiary": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-tertiary-fixed": "#351000",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdbcc",
        "on-secondary-fixed-variant": "#43474d",
        "on-secondary-fixed": "#181c21",
        "on-secondary-container": "#61656b",
      },
      fontFamily: {
        "headline-xl": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"]
      },
      fontSize: {
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}